# Generated by Django 3.2.7 on 2021-10-02 08:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 2, 8, 17, 23, 256162, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
