# Generated by Django 3.2.7 on 2021-10-02 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_event_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='date',
        ),
    ]
